apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: ticketboard
  labels:
    app: backend
    component: api
data:
  NODE_ENV: "production"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "ticketboard"
  DB_USER: "postgres"
  CORS_ORIGIN: "http://localhost:3000,http://localhost"
  JWT_EXPIRES_IN: "7d"
  PORT: "3000"
