apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ticketboard

resources:
  - configmap.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/part-of: ticketboard
  app.kubernetes.io/component: api
  app.kubernetes.io/managed-by: kustomize

images:
  - name: localhost:5000/backend
    newTag: latest
