apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: ticketboard
  labels:
    app: backend
    component: api
type: Opaque
data:
  DB_PASSWORD: bXlzZWNyZXRwYXNzd29yZA== # base64 encoded 'mysecretpassword'
  JWT_SECRET: c3VwZXJzZWNyZXRqd3RzZWNyZXQ= # base64 encoded 'supersecretjwtsecret'
