apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ticketboard

resources:
- ../../base

patches:
- path: backend-patch.yaml
  target:
    kind: Deployment
    name: backend
- path: frontend-patch.yaml
  target:
    kind: Deployment
    name: frontend

images:
- name: ticketboard-backend
  newName: $DOCKERHUB_USERNAME/ticketboard-backend
  newTag: latest
- name: ticketboard-frontend
  newName: $DOCKERHUB_USERNAME/ticketboard-frontend
  newTag: latest
