apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ticketboard

bases:
  - ../../base
  - ../../database
  - ../../backend
  - ../../frontend

patchesStrategicMerge:
  - backend-patch.yaml

commonLabels:
  environment: development
