apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ticketboard

bases:
  - ../../base

patchesStrategicMerge:
  - backend-patch.yaml

images:
  - name: ghost0/ticketboard-backend
    newTag: latest
  - name: ghost0/ticketboard-frontend
    newTag: latest
