apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ticketboard

bases:
  - ../../base
  - ../../database
  - ../../backend
  - ../../frontend

commonLabels:
  environment: production

patchesStrategicMerge:
  - backend-patch.yaml
  - frontend-patch.yaml
