apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ticketboard

resources:
  - namespace.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: ticketboard
  app.kubernetes.io/managed-by: kustomize
